"""empty message

Revision ID: 449cb7d0f60d
Revises: 3c51ef93b8c0
Create Date: 2021-09-13 17:40:02.573519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449cb7d0f60d'
down_revision = '3c51ef93b8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Todo', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Todo', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
