"""empty message

Revision ID: 823997db1356
Revises: 
Create Date: 2021-09-11 13:52:15.740954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823997db1356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE "Todo" SET completed = False WHERE completed IS NULL;')

    op.alter_column('Todo', 'completed', nullable=False)
    
    #op.excecute('ALTER TABLE Todo ADD completed;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Todo', 'completed')
    # ### end Alembic commands ###
