"""empty message

Revision ID: 9ef0fce9744b
Revises: 823997db1356
Create Date: 2021-09-11 17:02:30.363085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef0fce9744b'
down_revision = '823997db1356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Todo', 'date')
    # ### end Alembic commands ###
